input.onButtonPressed(Button.A, function on_button_pressed_a() {
    BEP.setLedColor(0xFF0000)
    basic.pause(1000)
    BEP.setLedColor(0x00FF00)
    basic.pause(1000)
    BEP.setLedColor(0x0000FF)
    basic.pause(1000)
})
input.onButtonPressed(Button.AB, function on_button_pressed_ab() {
    BEP.ledClear()
})
input.onButtonPressed(Button.B, function on_button_pressed_b() {
    BEP.startFlash(0xFF8000, 500)
})
basic.forever(function on_forever() {
    basic.showIcon(IconNames.Heart)
    BEP.setLedColor(0xFF0000)
    BEP.servoWrite(BEP.Servos.Righteye, 0)
    BEP.servoWrite(BEP.Servos.Lefteye, 0)
    BEP.servoWrite(BEP.Servos.Yellowgear, 0)
    BEP.servoWrite(BEP.Servos.Righteyebrow, 0)
    BEP.servoWrite(BEP.Servos.Lefteyebrow, 0)
    basic.pause(1000)
    basic.showIcon(IconNames.Yes)
    BEP.setLedColor(0x00FF00)
    BEP.servoWrite(BEP.Servos.Righteye, 2)
    BEP.servoWrite(BEP.Servos.Lefteye, 2)
    BEP.servoWrite(BEP.Servos.Yellowgear, 2)
    BEP.servoWrite(BEP.Servos.Righteyebrow, 2)
    BEP.servoWrite(BEP.Servos.Lefteyebrow, 2)
    basic.pause(1000)
})
